### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by bhumilsarvaiya** [MostlyJS/mostly-feathers#1]
Can you give few examples how to use this. In which file am I supposed to write the latter code?

**Comment by forafish** [comment]
There are few document on how to use right now. You could look into the demo project now on how to use it.

* [Mostly-demos](https://github.com/MostlyJS/mostly-demos)

More advanced usage you can also see

* [mostly-admin-services](https://github.com/MostlyJS/mostly-admin-services)
* [mostly-auth-services](https://github.com/MostlyJS/mostly-auth-services)

Which is part of the in-progress work for a microservices admin dashboard, [mostly-elements](https://github.com/MostlyJS/mostly-elements)
